version: "3.9"

services:
  sonarqube-community:
    build:
      dockerfile: Dockerfile.sonarqube

    image: ${REGISTRY}/sonarqube/sonarqube:community

    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

    ports:
      - "9000:9000"

    networks:
      - sonarqube
      - devops

    restart: always

    container_name: sonarqube-community

  postgres-db:
    build:
      dockerfile: Dockerfile.postgres

    image: ${REGISTRY}/postgres/postgres:15

    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar

    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

    networks:
      - sonarqube
      - devops

    restart: always

    container_name: postgres-db


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:


networks:
  sonarqube:
  devops:
    name: devops
    external: true

#Must configure to meet requirements:
# https://docs.sonarsource.com/sonarqube/latest/requirements/prerequisites-and-overview/