# docker run -p 8080:8080 -p 50000:50000 \
# --restart=always -v jenkins_home:/var/jenkins_home \
# -v /var/run/docker.sock:/var/run/docker.sock \
# --network host --name jenkins-master
# jenkins/jenkins
#Create master and ssh agent

version: "3.9"
services:
  jenkins-master:
    build:
      dockerfile: master/Dockerfile.master
      
    image: ${REGISTRY}/jenkins/master:jdk17

    container_name: jenkins-master

    ports:
      - "8080:8080"
      - "50000:50000"

    restart: "always"

    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"

    network_mode: "host"


  jenkins-agent-cloud:
    build:
      dockerfile: agents/Dockerfile.agent.cloud
      
    image: ${REGISTRY}/jenkins/agent-cloud:jdk17

    container_name: jenkins-agent-cloud


volumes:
  jenkins_home: