#docker build --build-arg DOCKER_GROUP_ID=$(stat -c '%g' /var/run/docker.sock) -t jenkins-ssh-agent -f Dockerfile.agent.ssh .

#Container run:
# docker run -d --group-add $(stat -c '%g' /var/run/docker.sock) \
# --name=jenkins-agent -p 23:22 \
# -e "JENKINS_AGENT_SSH_PUBKEY=$(cat ~/.ssh/jenkins_agent_key.pub)" \
# -v /var/run/docker.sock:/var/run/docker.sock \
# --restart=on-failure jenkins-ssh-agent

FROM jenkins/ssh-agent:jdk11

USER root

# Add Docker's official GPG key:
RUN apt-get -y update
RUN apt-get -y install ca-certificates curl gnupg
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

#Install Docker CLI
RUN apt-get -y update
RUN apt-get -y install docker-ce-cli jq wget

ARG DOCKER_GROUP_ID

#--group-add $(stat -c '%g' /var/run/docker.sock) doesnt work in ssh
# If jenkins already in group id then comment steps:
RUN groupadd -g ${DOCKER_GROUP_ID} host-docker
RUN usermod -aG host-docker jenkins

USER jenkins