## docker build -t devops-nginx:1.27.4-bookworm-perl -f Dockerfile .
## or ${REGISTRY}/devops/devops-nginx:1.27.4-bookworm-perl

FROM nginx:1.27.4-bookworm-perl

COPY nginx.conf /etc/nginx/conf.d/default.conf