# docker run -p 8080:8080 -p 50000:50000 --restart=always -v jenkins_home:/var/jenkins_home jenkins/jenkins
#Create master and ssh agent

version: "3.9"
services:
  jenkins-master:
    build:
      dockerfile: master/Dockerfile.master

      args:
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID}
      
    image: ${REGISTRY}/jenkins/master:jdk17

    container_name: jenkins-master

    ports:
      - "8080:8080"
      - "50000:50000"

    networks:
      - jenkins
      - devops

    restart: "always"

    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"

    group_add:
     - ${DOCKER_GROUP_ID}


  jenkins-agent-ssh:
    build:
      dockerfile: agents/Dockerfile.agent.ssh
      
      args:
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID}
      
    image: ${REGISTRY}/jenkins/agent-ssh:jdk11

    container_name: jenkins-agent-ssh

    ports:
      - "23:22"

    networks:
      - jenkins
      - devops

    restart: "always"

    volumes:
      - "jenkins-agent-ssh_home:/home/jenkins/agent"
      - "/var/run/docker.sock:/var/run/docker.sock"

    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}

    group_add:
     - ${DOCKER_GROUP_ID}


  jenkins-agent-cloud:
    build:
      dockerfile: agents/Dockerfile.agent.cloud
      
    image: ${REGISTRY}/jenkins/agent-cloud:jdk17

    container_name: jenkins-agent-cloud


volumes:
  jenkins_home:
  jenkins-agent-ssh_home:

networks:
  jenkins:
  devops:
    name: devops
    external: true