version: '3.9'

services:
  docker-registry-ui:
    build:
      dockerfile: Dockerfile.registry.ui
      
    image: ${REGISTRY}/docker/registry-ui:main

    restart: always
    
    ports:
      - 81:80
    
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - REGISTRY_SECURED=false
      - REGISTRY_URL=http://localhost:5000
    
    container_name: docker-registry-ui
    
    networks:
      - docker-registry
      - devops

  docker-registry-server:
    build:
      dockerfile: Dockerfile.registry
      
    image: ${REGISTRY}/docker/registry:2

    restart: always

    ports:
      - 5000:5000

    environment:
       - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['*']
       - REGISTRY_STORAGE_DELETE_ENABLED=true
       - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=[HEAD,GET,OPTIONS,DELETE]
       - REGISTRY_HTTP_HEADERS_Acces-Control-Allow-Credentials=[true]
       - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=[Authorization,Accept,Cache-Control]
       - REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers=[Docker-Content-Digest]
    
    volumes:
      - docker_registry_data:/var/lib/registry

    container_name: docker-registry-server

    networks:
      - docker-registry
      - devops

volumes:
  docker_registry_data:

networks:
  docker-registry:
  devops:
    name: devops
    external: true